spring:
  data:
    mongodb:
      uri: mongodb://database:27017/activemq-demo
      repositories:
        enabled: true
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    packages:
      trust-all: true
