spring:
  data:
    mongodb:
      uri: mongodb://0.tcp.ngrok.io:10250/activemq-demo
      repositories:
        enabled: true
  activemq:
    broker-url: tcp://2.tcp.ngrok.io:10221
    user: admin
    password: admin
    packages:
      trust-all: true
