server:
  port: 8081
spring:
  application:
    name: KAFKA_PRODUCER
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        output:
          destination: kafkaExample
