version: "3.7"

services:

  service:
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    container_name: service
    ports:
      - 8080:8080
    depends_on:
      - activemq
      - database
    restart: always

  activemq:
    image: webcenter/activemq
    container_name: activemq
    ports:
      - 8161:8161
    environment:
      ACTIVEMQ_STATIC_QUEUES: authentication
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  database:
    image: mongo:latest
    restart: always
    container_name: database
